FROM node:18-alpine

# Create the directory for the app and set permissions
RUN mkdir -p /home/node/app/node_modules && \
    chown -R node:node /home/node/app

# Switch to the node user
USER node

# Set the working directory
WORKDIR /home/node/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install 

# Copy the application code
COPY --chown=node:node . .

# Expose port
EXPOSE 8080

# Run the application
CMD ["node", "app.js"]
